"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup


class CONFIG:
    VERSION = '1.0.0'
    PLATFORM = 'darwin-x86_64'
    executable_stub = "/Library/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib"
    APP_NAME = f"voicebridge_{VERSION}_{PLATFORM}"
    APP = ['voicebridge.py']
    DATA_FILES = ['assets', 'recordings']

    OPTIONS = {
        'argv_emulation': False,
        'iconfile': 'assets/voicebridgeLogo.png',
        'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': APP_NAME,
            'CFBundleVersion': VERSION,
            'CFBundleShortVersionString': VERSION,
            'PyRuntimeLocations': [
                executable_stub,
                # also the executable can look like this:
                # '@executable_path/../Frameworks/libpython3.4m.dylib',
            ]
        }
    }


def main():
    setup(
        name=CONFIG.APP_NAME,
        app=CONFIG.APP,
        data_files=CONFIG.DATA_FILES,
        options={'py2app': CONFIG.OPTIONS},
        setup_requires=['py2app'],
        py_modules=[]
    )


if __name__ == '__main__':
    main()
